### PR TITLE
Numerous changes

### PR DESCRIPTION
**Pull request by themox**
Numerous changes, mostly under the hood.  Added sorting by several configurable methods, and added ability to configure icons from config file.

### CODE REVIEW

**Comment by jayked** [comment]
Thank you for some maintenance. Unfortunately some functionalities no longer work after I checked out your pull request. Whenever I update the status of a task it does not get updated and the icons are not being shown.

**Comment by themox** [comment]
Ok - can you post your custom.css and config.js files as well as any log outputs?  That will help me see what your issue might be.

**Comment by themox** [comment]
I see you've made many of these changes separately.  Closing this.

**Comment by jayked** [comment]
Sorry, wanted to mention it to you but I was quite in a hurry that 2 days. I saw the changes and thought they were a good idea so I applied them manually. So thank you for the ideas.

**Pull request closed without merging**
